apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hostendpoint-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hostendpoint-operator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "hostendpoint-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "hostendpoint-operator.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "hostendpoint-operator.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: LOG_LEVEL
              value: {{ .Values.config.logLevel | quote }}
            - name: SCAN_INTERVAL_SECONDS
              value: {{ .Values.config.scanIntervalSeconds | quote }}
            - name: OPERATOR_ID
              value: {{ .Values.config.operatorId | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          
          # We mount a writable in-memory volume to the path we created in the Dockerfile.
          volumeMounts:
            - name: tmp-writable
              mountPath: /tmp/writable_tmp
      
      # Define the in-memory volume.
      volumes:
        - name: tmp-writable
          emptyDir:
            medium: Memory

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}